# Optimized Fly.io config for video rendering workloads
app = "social-story-renderer"
primary_region = "iad"

[build]

[env]
  # Memory optimizations
  MALLOC_TRIM_THRESHOLD = "131072"
  MALLOC_MMAP_THRESHOLD = "131072"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  # Optimized for video processing: 1GB RAM, 2 CPUs
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2

[processes]
  app = "uvicorn app:app --host 0.0.0.0 --port 8080 --workers 1"


