[project]
name = "render-worker"
version = "0.1.0"
description = "FFmpeg render worker for Social Story"
requires-python = ">=3.10"
dependencies = [
  "fastapi==0.115.0",
  "uvicorn[standard]==0.30.6",
]


